---
dependency:
  name: galaxy

driver:
  name: docker

lint:
  name: yamllint

platforms:
  - name: ansible-role-git-credential-manager-ubuntu-max
    image: ubuntu:18.04

provisioner:
  name: ansible
  playbooks:
    converge: ../default/playbook.yml
  lint:
    name: ansible-lint

scenario:
  name: ubuntu-max

verifier:
  name: testinfra
  lint:
    name: flake8
